require("options")
require("plugins")
require("keybindings")
require("colorscheme")

require("modules.lsp")
require("modules.editor")
require("modules.tools")
require("modules.ui")
require("modules.vcs")
