require("options")
require("plugins")
require("keybindings")
require("colorscheme")
require("lsp")

require("plugin-config.autopairs")
require("plugin-config.comment")
require("plugin-config.gitsigns")
require("plugin-config.impatient")
require("plugin-config.indentline")
require("plugin-config.lualine")
require("plugin-config.nvim-tree")
require("plugin-config.telescope")
require("plugin-config.todo-comments")
require("plugin-config.toggleterm")
require("plugin-config.transparent")
require("plugin-config.treesitter")
