-- Clipboard image plumbing for the composer.
--
-- Why this exists at all: an image cannot travel through the composer's only
-- channel to the agent, which is the pty. The agent CLIs solve this by reading
-- the system clipboard themselves -- Claude Code shells out to
-- `osascript -e 'the clipboard as «class PNGf»'`, Codex uses NSPasteboard --
-- and base64 the result straight into their API request. Nvim has no way to
-- inject into that request, so it does the next best thing: it hands the image
-- back to the TUI through the mechanism the TUI already has, by putting the
-- image on the clipboard and sending the keystroke that makes the TUI read it.
--
--   Claude Code:  ctrl+v -> "chat:imagePaste"
--   Codex:        "Paste an image with Ctrl+V to attach it to your next message."
--
-- Both are the same byte, 0x16.
--
-- The temp-file round trip is not optional. `clipboard = "unnamedplus"`
-- (lua/options.lua:50) means every yank, delete or change inside the composer
-- overwrites the system clipboard, so an image left sitting there while a prompt
-- is being written would be gone by the time it was sent.

local M = {}

-- How long the TUI needs after 0x16 before it is ready for more input. The
-- clipboard read shells out to osascript on the agent's side, so this is a
-- process spawn, not just a redraw.
local INGEST_MS = 250

local function is_macos()
  return vim.uv.os_uname().sysname == "Darwin"
end

---@param script string[] one AppleScript line per element
local function osascript(script)
  local cmd = { "osascript" }
  for _, line in ipairs(script) do
    cmd[#cmd + 1] = "-e"
    cmd[#cmd + 1] = line
  end
  return vim.system(cmd, { text = true }):wait()
end

-- Paths are interpolated into AppleScript source, which has no equivalent of
-- shellescape. Every path here is generated by tempname(), so this is a
-- tripwire rather than a filter.
local function safe_path(path)
  return type(path) == "string" and path ~= "" and not path:find('["\\\n]')
end

---Is there an image on the system clipboard right now?
---@return boolean
function M.has_image()
  if not is_macos() then return false end
  local result = osascript({ "clipboard info" })
  return result.code == 0
    and result.stdout ~= nil
    and result.stdout:find("PNGf", 1, true) ~= nil
end

---Write the clipboard image to `path` as PNG.
---@param path string
---@return boolean ok
---@return string|nil err
function M.save_image(path)
  if not is_macos() then
    return false, "clipboard images are only wired up for macOS"
  end
  if not safe_path(path) then
    return false, "refusing to use a path containing quotes, backslashes or newlines"
  end

  local result = osascript({
    "set png_data to (the clipboard as «class PNGf»)",
    ('set fp to open for access POSIX file "%s" with write permission'):format(path),
    "set eof fp to 0",
    "write png_data to fp",
    "close access fp",
  })
  if result.code ~= 0 then
    return false, vim.trim(result.stderr or "osascript failed")
  end

  local stat = vim.uv.fs_stat(path)
  if not stat or stat.size == 0 then
    return false, "clipboard produced an empty image"
  end
  return true
end

---Put a PNG file back on the system clipboard.
---@param path string
---@return boolean ok
---@return string|nil err
function M.restore_image(path)
  if not is_macos() then
    return false, "clipboard images are only wired up for macOS"
  end
  if not safe_path(path) then
    return false, "refusing to use a path containing quotes, backslashes or newlines"
  end
  if not vim.uv.fs_stat(path) then
    return false, "image file is gone: " .. path
  end

  local result = osascript({
    ('set the clipboard to (read (POSIX file "%s") as «class PNGf»)'):format(path),
  })
  if result.code ~= 0 then
    return false, vim.trim(result.stderr or "osascript failed")
  end
  return true
end

---Feed each image to the agent TUI, then run `done`.
---
---Sequential and deferred rather than a loop: each 0x16 makes the TUI spawn its
---own clipboard reader, and the next image cannot be placed on the clipboard
---until that read has finished.
---@param channel integer terminal job channel
---@param paths string[]
---@param done fun()
function M.attach(channel, paths, done)
  local index = 0

  local function step()
    index = index + 1
    local path = paths[index]
    if not path then
      -- The TUI writes each attachment inline as "[Image #N]" with no trailing
      -- separator, so prompt text sent next would run straight into it. One
      -- space keeps the submitted line readable.
      if index > 1 then
        vim.api.nvim_chan_send(channel, " ")
      end
      done()
      return
    end

    local ok, err = M.restore_image(path)
    if not ok then
      vim.notify(("Could not attach image: %s"):format(err), vim.log.levels.WARN)
      step()
      return
    end

    -- 0x16 is the byte ctrl+v produces. It carries no data: it only tells the
    -- TUI to go read the clipboard itself.
    vim.api.nvim_chan_send(channel, "\22")
    vim.defer_fn(step, INGEST_MS)
  end

  step()
end

---Where composer images are staged. One directory per Nvim process so a crash
---leaves an obvious, self-identifying pile rather than scattered temp files.
---@return string
function M.staging_dir()
  local dir = ("%s/nvim-ai-images-%d"):format(vim.fn.stdpath("cache"), vim.fn.getpid())
  vim.fn.mkdir(dir, "p")
  return dir
end

return M
